// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'remove': string;
  'restore': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
