// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'admin-select__input': string;
  'admin-select__radio-button': string;
  'admin-select__radio-button--active': string;
  'admin-select__radio-button--title': string;
  'admin-select__radio-button--wrap': string;
  'admin-select__wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
