// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'account--login': string;
  'account__button': string;
  'account__button--position': string;
  'account__container': string;
  'account__ico-eye': string;
  'account__input': string;
  'account__input--required': string;
  'account__input-section': string;
  'account__input-section--require': string;
}
export const cssExports: CssExports;
export default cssExports;
