// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addSelect': string;
  'project__button-save-position': string;
  'project__field': string;
  'project__field--description': string;
  'project__row': string;
}
export const cssExports: CssExports;
export default cssExports;
