// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'input--password': string;
  'input--required': string;
  'input--textarea': string;
  'input__ico-eye': string;
  'input__label': string;
  'input__label--normal': string;
  'input__label--required': string;
  'input__wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
