// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar': string;
  'sidebar--close': string;
  'sidebar__arrows': string;
  'sidebar__arrows--close': string;
  'sidebar__arrows--close-fix': string;
  'sidebar__arrows--open': string;
  'sidebar__arrows--style': string;
  'sidebar__mask': string;
  'sidebar__mask--close': string;
  'sidebar__menu': string;
  'sidebar__menu--item': string;
  'sidebar__menu--link': string;
  'sidebar__menu--text': string;
  'sidebar__menu--title': string;
}
export const cssExports: CssExports;
export default cssExports;
