// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'user-profile__item': string;
  'user-profile__item--top-line': string;
  'user-profile__item--value': string;
  'user-profile__row': string;
  'user-profile__text': string;
  'user-profile__text--bold': string;
  'user-profile__text--section': string;
}
export const cssExports: CssExports;
export default cssExports;
