// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button--disabled': string;
  'button--remove': string;
  'button--update': string;
}
export const cssExports: CssExports;
export default cssExports;
