// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header--container': string;
  'header__ico--home': string;
  'header__menu-list': string;
  'header__menu-list--element': string;
  'header__menu-list--link': string;
}
export const cssExports: CssExports;
export default cssExports;
