// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'flagEN': string;
  'flagPL': string;
  'header': string;
  'home': string;
  'item': string;
  'link': string;
  'list': string;
}
export const cssExports: CssExports;
export default cssExports;
