// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'project-profile__item': string;
  'project-profile__item--description': string;
  'project-profile__item--hours': string;
  'project-profile__item--hours-input': string;
  'project-profile__item--title-list': string;
  'project-profile__item--top-line': string;
  'project-profile__item--value': string;
  'project-profile__row': string;
  'project-profile__row--user-list': string;
  'project-profile__row--with-button': string;
  'project-profile__text': string;
  'project-profile__text--bold': string;
  'project-profile__text--section': string;
}
export const cssExports: CssExports;
export default cssExports;
