// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'list': string;
  'list__cell': string;
  'list__cell--normal': string;
  'list__cell--small': string;
  'list__cell--wide': string;
  'list__label': string;
  'list__message': string;
  'list__radio-button': string;
  'list__radio-button--active': string;
  'list__radio-button--radio': string;
  'list__radio-button--wrap': string;
  'list__row': string;
  'list__row--link': string;
  'list__row--title': string;
  'row': string;
  'title': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
