// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'user__field-wrap': string;
  'user__field-wrap--select-admin': string;
  'user__row': string;
  'user__row--save-button-wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
